name: global_diaspora_events
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Core & Backend
  supabase_flutter: ^2.8.3
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  
  # Models & Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  
  # Navigation & Routing
  go_router: ^17.1.0
  
  # Geospatial & Maps
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  
  # UI & Assets
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  
  # Storage (Offline-first)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  timeago: ^3.7.0
  fpdart: ^1.2.0
  google_sign_in: ^7.2.0
  google_fonts: ^8.0.1
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  app_links: ^7.0.0
  share_plus: ^12.0.1
  flutter_animate: ^4.5.2
  dynamic_color: ^1.8.1
  shimmer: ^3.0.0
  google_maps_flutter: ^2.14.2
  image_picker: ^1.2.1

dependency_overrides:
  meta: 1.18.1
  analyzer: 10.0.2
  _fe_analyzer_shared: 94.0.0
  analyzer_buffer: 0.3.1
  dart_style: 3.1.5
  app_links: 7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.11.1
  riverpod_generator: ^4.0.3
  freezed: ^3.2.5
  json_serializable: ^6.12.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
