// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm276bRteK8yWoxIczSnCWO9mTh1uY2E8',
    appId: '1:355224727058:web:911f98d3b4ec7f8756f2cb',
    messagingSenderId: '355224727058',
    projectId: 'global-diaspora-events',
    authDomain: 'global-diaspora-events.firebaseapp.com',
    storageBucket: 'global-diaspora-events.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnPI7iXoVLOs5sHakV-YucmPalTFuW4PU',
    appId: '1:355224727058:android:d69d4fc74a1a7a6356f2cb',
    messagingSenderId: '355224727058',
    projectId: 'global-diaspora-events',
    storageBucket: 'global-diaspora-events.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgcOTv_gqX56dxu7iJau7IFnLGfhkzm4A',
    appId: '1:355224727058:ios:b2c10e7d3c5bca3656f2cb',
    messagingSenderId: '355224727058',
    projectId: 'global-diaspora-events',
    storageBucket: 'global-diaspora-events.firebasestorage.app',
    iosBundleId: 'com.gde.globalDiasporaEvents',
  );
}
